services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RAILS_ENV=production
      # To enable HTTPS & automatic TLS w/Let's Encrypt
      # - TLS_DOMAIN=your.external.domain
    env_file: .env
    # To generate .env secrets, run gen_secrets.sh
    volumes:
      - "./storage/:/rails/storage"
      - "./db:/rails/db"
      - "./log:/rails/log"
