services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    # To generate .env secrets, run gen_secrets.sh
    volumes:
      - ${STATE_DIRECTORY:-./storage/}:/rails/storage
      - ${LOGS_DIRECTORY:-./log}:/rails/log
