services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RAILS_ENV=production
      # To enable HTTPS & automatic TLS w/Let's Encrypt
      # - TLS_DOMAIN=your.external.domain
    env_file: .env
    # To generate .env secrets, run gen_secrets.sh
    volumes:
      - "${STATE_DIRECTORY:-./storage/:/rails/storage}"
      - "${LOGS_DIRECTORY:-./log:/rails/log}"
