services:
  united:
    build: "."
    depends_on:
      redict:
        condition: "service_started"
        required: false
    env_file:
      - ".env"
    environment:
      - "RAILS_ENV=production"
      - "DATABASE_URL=sqlite3:///db/production.sqlite3"
      - "PORT=3000"
    restart: "unless-stopped"
    stop_grace_period: "3s"
    tty: true
    volumes:
      - "db:/db"
    ports:
      - "3000:3000"
volumes:
  db: {}
