databases:
  - name: united
    databaseName: united
    user: united
    plan: free

services:
  - type: web
    name: united
    runtime: docker
    plan: free
    image:
      url: docker.io/reesericci/united:latest
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: united
          property: connectionString
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: RAILS_ENV
        value: production