databases:
  - name: united
    databaseName: united
    user: united
    plan: free

services:
  - type: web
    name: united
    runtime: ruby
    plan: free
    buildCommand: "./render.sh"
    startCommand: "bundle exec rails db:migrate && bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: united
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: RAILS_ENV
        value: production