name: Build release container
on:
  release: 
    types: [published, edited]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: https://codeberg.org/umglurf/kaniko-action@main
        with:
          credentials: |
            codeberg.org=reesericci:${{ secrets.CODEBERG_TOKEN }}          
          destinations: |
            codeberg.org/${{ github.repository }}:${{ github.event.release.tag_name }}      
          push: 'true'
          docker_file: "Containerfile"