on: [push]
jobs:
  build:
    runs-on: docker
    container:
      image: goltzsche/podman:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: podman build -t codeberg.org/reesericci/united:latest .
      - name: Login to Codeberg registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | podman login --username reesericci codeberg.org
      - name: Push image
        run: podman push codeberg.org/reesericci/united:latest