name: Build container
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Buildah Action
      id: build-image
      uses: https://github.com/redhat-actions/buildah-build@v2
      with:
        image: codeberg.org/reesericci/united
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Containerfile
    - name: Push to codeberg
      id: push-to-codeberg
      uses: https://github.com/redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: codeberg.org/reesericci
        username: reesericci
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"