on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mgoltzsche/podman:latest
    steps:
      - name: Setup node
        uses: https://github.com/actions/setup-node@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: podman build -t codeberg.org/reesericci/united:latest .
      - name: Login to Codeberg registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | podman login --username reesericci codeberg.org
      - name: Push image
        run: podman push codeberg.org/reesericci/united:latest