name: Build release container
on:
  release: 
    types: [published, edited]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build for Codeberg
        uses: https://codeberg.org/umglurf/kaniko-action@main
        with:
          cache: true
          cache_repo: codeberg.org/${{ github.repository }}/cache
          credentials: |
            codeberg.org=reesericci:${{ secrets.CODEBERG_TOKEN }}  
          destinations: |
            codeberg.org/${{ github.repository }}:${{ github.event.release.tag_name }}
          push: 'true'
          docker_file: "Containerfile"
      - name: Build for Docker Hub
        uses: https://codeberg.org/umglurf/kaniko-action@main
        with:
          cache: true
          cache_repo: codeberg.org/${{ github.repository }}/cache
          credentials: |
            docker.io=reesericci:${{ secrets.DOCKER_PASSWORD }}        
          destinations: |
            docker.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          push: 'true'
          docker_file: "Containerfile"