default: &default
  adapter: solid_cable
  polling_interval: 5.second
  keep_messages_around_for: 1.day
  connects_to:
    database:
      writing: cable
      reading: cable

development:
  <<: *default
  silence_polling: true

test:
  adapter: test

production:
  <<: *default
  polling_interval: 0.5.seconds