default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
 
primary: &primary
  <<: *default
  database: storage/<%= ENV["RAILS_ENV"] || "development" %>.sqlite3
 
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: storage/queue.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: storage/cache.sqlite3

cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate
  database: storage/cable.sqlite3

production: &production
  primary: *primary
  queue: *queue
  cache: *cache
  cable: *cable
 
development:
  <<: *production
 
test:
  <<: *primary
  database: db/test.sqlite3
 