default: &default
  dispatchers:
    - polling_interval: 10
      batch_size: 500
      recurring_tasks:
        expirable_advisement:
          class: Expirable::AdvisementJob
          args: []
          schedule: every hour
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 5

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default

demo:
  dispatchers:
    - polling_interval: 10
      batch_size: 500
      recurring_tasks:
        expirable_advisement:
          class: Expirable::AdvisementJob
          args: []
          schedule: every hour
        demo_reset:
          class: Demo::ResetJob
          args: []
          schedule: "0,30 * * * *"
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 5
